require:
  - rubocop-rails
  - rubocop-rspec

AllCops:
  NewCops: disable

Style/Documentation:
  Enabled: false

Metrics/AbcSize:
  Exclude:
    - db/migrate/*

Metrics/BlockLength:
  Exclude:
    - config/environments/*
    - db/migrate/*
    - spec/**/*

Metrics/MethodLength:
  Exclude:
    - db/migrate/*

RSpec/MultipleExpectations:
  Enabled: false
