version: "2.1"
orbs:
  ruby: circleci/ruby@1.7.1
  heroku: circleci/heroku@1.2.6
jobs:
  build:
    docker:
      - image: cimg/ruby:3.1.1
    steps:
      - checkout
      - ruby/install-deps
  static_analysis:
    docker:
      - image: cimg/ruby:3.1.1
    steps:
      - checkout
      - run:
          name: touch .env.test
          command: touch .env.test
      - run:
          name: Load env from .env.test
          command: 'cat .env.test | awk ''{print "export " $0}'' >> $BASH_ENV'
      - ruby/install-deps
      - ruby/rubocop-check:
          format: progress
          label: Inspecting with Rubocop
          parallel: true
  test:
    docker:
      - image: cimg/ruby:3.1.1
      - environment:
          POSTGRES_DB: rails_test_db
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
        image: cimg/postgres:11.14
      - image: cimg/redis:6.2.6
    environment:
      BUNDLE_JOBS: 3
      BUNDLE_RETRY: 3
      PGHOST: localhost
      PGPASSWORD: postgres
      PGUSER: postgres
      RAILS_ENV: test
    parallelism: 4
    steps:
      - checkout
      - run:
          name: touch .env.test
          command: touch .env.test
      - run:
          name: Load env from .env.test
          command: 'cat .env.test | awk ''{print "export " $0}'' >> $BASH_ENV'
      - ruby/install-deps
      - run:
          command: dockerize -wait tcp://localhost:5432 -timeout 1m
          name: Wait for Postgres
      - run:
          command: dockerize -wait tcp://localhost:6379 -timeout 1m
          name: Wait for Redis
      - run: cp .circleci/database.yml config/database.yml
      - run:
          command: bundle exec rails db:schema:load --trace
          name: Database setup
      - ruby/rspec-test
  deploy_to_heroku:
    steps:
      - checkout
      - heroku/deploy-via-git:
          filters:
            branches:
              only: main
workflows:
  build_and_test:
    jobs:
      - build
      - static_analysis:
          requires:
            - build
      - test:
          requires:
            - build
  heroku_deploy:
    jobs:
      - deploy_to_heroku:
          requires:
            - build
            - static_analysis
            - test
